export interface TFreeBot {
    id: string;
    name: string;
    description: string;
    category: 'Official' | 'Hybrid' | 'Normal' | 'Automatic';
    xmlPath: string;
    isPremium: boolean;
    isNew?: boolean;
    icon?: string;
    color?: string;
}

export const FREE_BOTS_DATA: TFreeBot[] = [
    // HYBRID BOTS (Elite Strategies)
    {
        id: 'guardian-under',
        name: 'The Guardian Under',
        description: 'Elite Sequential Under 9 -> Under 8 strategy with Under 4 recovery and market intelligence.',
        category: 'Official',
        xmlPath: 'Official Bots/Guardian_Under.xml',
        isPremium: true,
        isNew: true,
        color: '#ffdd00',
    },
    {
        id: 'titan-over',
        name: 'The Titan Over',
        description: 'Elite Sequential Over 0 -> Over 1 strategy with Over 5 recovery and market intelligence.',
        category: 'Official',
        xmlPath: 'Official Bots/Titan_Over.xml',
        isPremium: true,
        isNew: true,
        color: '#ffdd00',
    },
    {
        id: 'unstoppable-switcher',
        name: 'Unstoppable Even/Odd Switcher',
        description:
            'Automatically switches between Even and Odd with massive power analysis and strict pattern entry.',
        category: 'Official',
        xmlPath: 'Official Bots/Even_Odd_Auto_Switcher.xml',
        isPremium: true,
        isNew: true,
        color: '#ffdd00',
    },
    {
        id: 'compounding-bot',
        name: 'Compounding Bot',
        description: 'Reinvests winnings into the next stake for exponential growth.',
        category: 'Official',
        xmlPath: 'Official Bots/Compounding_Bot.xml',
        isPremium: true,
        isNew: true,
        color: '#ffdd00',
    },
    {
        id: 'over-under-compounding',
        name: 'The Titan Compounding',
        description: 'Elite Over 1,2 and Under 7,8 strategy with auto-switching and power compounding.',
        category: 'Official',
        xmlPath: 'Official Bots/Over_Under_Compounding.xml',
        isPremium: true,
        isNew: true,
        color: '#ffdd00',
    },
    {
        id: 'normal-speedbot-updated',
        name: 'SPEED BOT updated',
        description: 'Updated version of the popular speed bot strategy.',
        category: 'Normal',
        xmlPath: 'Normal Bots/SPEED BOT updated.xml',
        isPremium: false,
        color: '#3b82f6',
    },
    {
        id: 'hybrid-speedbot-entry',
        name: 'Speedbot with entry point',
        description: 'Elite Speedbot strategy with dynamic entry point logic.',
        category: 'Hybrid',
        xmlPath: 'Hybrid Bots/Speedbot with entry point.xml',
        isPremium: true,
        isNew: true,
        color: '#ffdd00',
    },
    {
        id: 'unstoppable-differ-bot',
        name: '🤑UNSTOPPABLE DIFFER BOT🤑',
        description: 'High-frequency differs strategy with unstoppable momentum.',
        category: 'Hybrid',
        xmlPath: 'Hybrid Bots/🤑UNSTOPPABLE DIFFER BOT🤑.xml',
        isPremium: true,
        isNew: true,
        color: '#10b981',
    },

    // AUTOMATIC BOTS (Standard Professional)
    {
        id: 'auto-even-odd-new',
        name: 'Official Even/Odd Bot',
        description: 'Advanced Even/Odd strategy with 100-tick analysis and pattern entry.',
        category: 'Official',
        xmlPath: 'Official Bots/Even_Odd_Bot.xml',
        isPremium: true,
        isNew: true,
        color: '#ffdd00',
    },
    {
        id: 'auto-over-under-new',
        name: 'Official Over/Under Bot',
        description: 'Predicts Over/Under based on market bias and increasing digit power.',
        category: 'Official',
        xmlPath: 'Official Bots/Over_Under_Bot.xml',
        isPremium: true,
        isNew: true,
        color: '#ffdd00',
    },
    {
        id: 'auto-differs-new',
        name: 'Official Differs Bot',
        description: 'Targets the least frequent digit in the last 50 ticks for high probability differs trading.',
        category: 'Official',
        xmlPath: 'Official Bots/Differs_Bot.xml',
        isPremium: true,
        isNew: true,
        color: '#ffdd00',
    },
    {
        id: 'auto-matches-new',
        name: 'Official Matches Bot',
        description: 'Predicts the most frequent digit in the last 50 ticks to catch matching digit correlations.',
        category: 'Official',
        xmlPath: 'Official Bots/Matches_Bot.xml',
        isPremium: true,
        isNew: true,
        color: '#ffdd00',
    },
    {
        id: 'sequential-under-recovery',
        name: 'Sequential Under Recovery',
        description: 'Sequential Under 9-8-7 strategy with advanced loss protection and market switching.',
        category: 'Official',
        xmlPath: 'Official Bots/Sequential_Under_Recovery.xml',
        isPremium: true,
        isNew: true,
        color: '#ffdd00',
    },
    {
        id: 'sequential-over-recovery',
        name: 'Sequential Over Recovery',
        description: 'Sequential Over 1-2-3 strategy with advanced loss protection and market switching.',
        category: 'Official',
        xmlPath: 'Official Bots/Sequential_Over_Recovery.xml',
        isPremium: true,
        isNew: true,
        color: '#ffdd00',
    },
    {
        id: 'premium-speedbot',
        name: 'Profithub Speedbot',
        description: 'Fast execution bot for volatility indices with smart martingale.',
        category: 'Normal',
        xmlPath: 'Normal Bots/Profithub Speedbot.xml',
        isPremium: true,
        color: '#ffdd00',
    },

    // SPECIALIZED BOTS
    {
        id: 'auto-over-0',
        name: 'Over 0 Bot',
        description: 'Specialized Over 0 strategy with auto market switching.',
        category: 'Official',
        xmlPath: 'Official Bots/Over_0_Bot.xml',
        isPremium: true,
        isNew: true,
        color: '#ffdd00',
    },
    {
        id: 'auto-over-1',
        name: 'Over 1 Bot',
        description: 'Specialized Over 1 strategy with auto market switching.',
        category: 'Official',
        xmlPath: 'Official Bots/Over_1_Bot.xml',
        isPremium: true,
        isNew: true,
        color: '#ffdd00',
    },
    {
        id: 'auto-over-2',
        name: 'Over 2 Bot',
        description: 'Specialized Over 2 strategy with auto market switching.',
        category: 'Official',
        xmlPath: 'Official Bots/Over_2_Bot.xml',
        isPremium: true,
        isNew: true,
        color: '#ffdd00',
    },
    {
        id: 'auto-over-3',
        name: 'Over 3 Bot',
        description: 'Specialized Over 3 strategy with auto market switching.',
        category: 'Official',
        xmlPath: 'Official Bots/Over_3_Bot.xml',
        isPremium: true,
        isNew: true,
        color: '#ffdd00',
    },
    {
        id: 'auto-under-9',
        name: 'Under 9 Bot',
        description: 'Specialized Under 9 strategy with auto market switching.',
        category: 'Official',
        xmlPath: 'Official Bots/Under_9_Bot.xml',
        isPremium: true,
        isNew: true,
        color: '#ffdd00',
    },
    {
        id: 'auto-under-8',
        name: 'Under 8 Bot',
        description: 'Specialized Under 8 strategy with auto market switching.',
        category: 'Official',
        xmlPath: 'Official Bots/Under_8_Bot.xml',
        isPremium: true,
        isNew: true,
        color: '#ffdd00',
    },
    {
        id: 'auto-under-7',
        name: 'Under 7 Bot',
        description: 'Specialized Under 7 strategy with auto market switching.',
        category: 'Official',
        xmlPath: 'Official Bots/Under_7_Bot.xml',
        isPremium: true,
        isNew: true,
        color: '#ffdd00',
    },
    {
        id: 'auto-under-6',
        name: 'Under 6 Bot',
        description: 'Specialized Under 6 strategy with auto market switching.',
        category: 'Official',
        xmlPath: 'Official Bots/Under_6_Bot.xml',
        isPremium: true,
        isNew: true,
        color: '#ffdd00',
    },
    {
        id: 'over-0123',
        name: 'Over 0-1-2-3 Strategy',
        description: 'Comprehensive Over strategy covering digits 0, 1, 2, and 3.',
        category: 'Official',
        xmlPath: 'Official Bots/Over_0123_Bot.xml',
        isPremium: true,
        isNew: true,
        color: '#ffdd00',
    },
    {
        id: 'under-9876',
        name: 'Under 9-8-7-6 Strategy',
        description: 'Comprehensive Under strategy covering digits 9, 8, 7, and 6.',
        category: 'Official',
        xmlPath: 'Official Bots/Under_9876_Bot.xml',
        isPremium: true,
        isNew: true,
        color: '#ffdd00',
    },
    {
        id: 'differs-rank-3',
        name: 'Differs Rank 3 Bot',
        description: 'Differs strategy utilizing Rank 3 logic.',
        category: 'Official',
        xmlPath: 'Official Bots/Differs_Rank3_Bot.xml',
        isPremium: true,
        isNew: true,
        color: '#ffdd00',
    },
    {
        id: 'rise-fall-super',
        name: 'Rise Fall Super Bot',
        description: 'Advanced Rise/Fall strategy.',
        category: 'Official',
        xmlPath: 'Official Bots/Rise_Fall_Super_Bot.xml',
        isPremium: true,
        isNew: true,
        color: '#ffdd00',
    },
    {
        id: 'smart-auto-24',
        name: 'Smart Auto 24/7',
        description: 'Continuous automated trading bot.',
        category: 'Official',
        xmlPath: 'Official Bots/SmartAuto24_Bot.xml',
        isPremium: true,
        isNew: true,
        color: '#ffdd00',
    },
    {
        id: 'alt-even-odd',
        name: 'Alternative Even/Odd',
        description: 'Alternative logic for Even/Odd trading.',
        category: 'Official',
        xmlPath: 'Official Bots/Bot_Even_Odd.xml',
        isPremium: true,
        isNew: false,
        color: '#ffdd00',
    },
    // NEW AUTOMATIC BOTS
    {
        id: 'autotrader',
        name: 'AUTOTRADER',
        description: 'Fully automated professional trading bot.',
        category: 'Automatic',
        xmlPath: 'Automatic/AUTOTRADER.xml',
        isPremium: true,
        color: '#ffdd00',
    },
    {
        id: 'las-vegas-pro',
        name: 'LAS VEGAS 💵 PRO ENGLISH',
        description: 'Premium Las Vegas style strategy for aggressive growth.',
        category: 'Automatic',
        xmlPath: 'Automatic/LAS VEGAS 💵💵 PRO ENGLISH..xml',
        isPremium: true,
        color: '#ffdd00',
    },
    {
        id: 'over-under-switcher',
        name: 'OVER UNDER AUTO SWITCHER',
        description: 'Smartly switches between Over and Under based on market trends.',
        category: 'Automatic',
        xmlPath: 'Automatic/OVER UNDER AUTO SWITCHER.xml',
        isPremium: true,
        color: '#ffdd00',
    },
    {
        id: 'over-under-automatic-x',
        name: 'OVER UNDER AUTOMATIC X',
        description: 'Automated Over/Under strategy with X-factor analysis.',
        category: 'Automatic',
        xmlPath: 'Automatic/OVER UNDER AUTOMATIC X .xml',
        isPremium: true,
        color: '#ffdd00',
    },
    {
        id: 'profithub-premium-ai',
        name: 'PROFITHUB PREMIUM A.I',
        description: 'Our most advanced AI-driven strategy for maximum consistency.',
        category: 'Automatic',
        xmlPath: 'Automatic/PROFITHUB PREMIUM A.I.xml',
        isPremium: true,
        isNew: true,
        color: '#ffdd00',
    },
    {
        id: 'profithub-rise-fall-auto',
        name: 'PROFITHUB RISE FALL AUTO',
        description: 'Automated Rise/Fall strategy with Profithub intelligence.',
        category: 'Automatic',
        xmlPath: 'Automatic/PROFITHUB RISE FALL AUTO.xml',
        isPremium: true,
        color: '#ffdd00',
    },
    {
        id: 'profithub-under-8-over-3',
        name: 'PROFITHUB UNDER 8 OVER 3 AUTO',
        description: 'Dual strategy targeting both Under 8 and Over 3.',
        category: 'Automatic',
        xmlPath: 'Automatic/PROFITHUB UNDER 8 OVER 3 AUTO.xml',
        isPremium: true,
        color: '#ffdd00',
    },
    {
        id: 'rise-fall-automatic-x',
        name: 'RISE AND FALL AUTOMATIC X',
        description: 'Fast-paced automated Rise and Fall with X-series entry.',
        category: 'Automatic',
        xmlPath: 'Automatic/RISE AND FALL AUTOMATIC X .xml',
        isPremium: true,
        color: '#ffdd00',
    },
    {
        id: 'profit-hub-pro',
        name: 'PROFIT HUB PRO',
        description: 'Professional grade Profit Hub strategy.',
        category: 'Normal',
        xmlPath: 'Normal Bots/PROFIT HUB PRO.xml',
        isPremium: true,
        color: '#ffdd00',
    },
];
